const DEFAULT = {
  MAX_EMAIL_SENDING_SIZE: 50,
  ORIGIN_EMAIL: 'marlodelatorre11@gmail.com',
  SECRET_KEY: 'SES-Secrets',
  SECRET_MANAGER_API_VERSION: '2017-10-17',
};

export const CONFIG = {
  AUTH_TOKEN: '',
  CHUNK_SIZE: DEFAULT.MAX_EMAIL_SENDING_SIZE,
  ORIGIN_EMAIL: DEFAULT.ORIGIN_EMAIL,
  SECRET_KEY: DEFAULT.SECRET_KEY,
  SECRET_MANAGER_API_VERSION: DEFAULT.SECRET_MANAGER_API_VERSION,
};
